### PR TITLE
Set rel="noopener noreferrer" property to all links with target="_blank"

### PR DESCRIPTION
**Pull request by PAPERPANKS**
## Changes

`... target="_blank" rel="noopener noreferrer" ...` 
- in reference to issue #54

### CODE REVIEW

**Comment by veelenga** [comment]
You are pretty fast. Give few minutes for testing :)

Be free to add yourself to the [list of contributors](https://github.com/crystal-community/crystal-ann#contributors)

**Review by veelenga — APPROVED** [review]

**Comment by PAPERPANKS** [comment]
It's my great privilege to be in contributor list but i will add myself after complete work

**Comment by veelenga** [comment]
@PAPERPANKS i'm ready to merge this PR. Could you please just do this on this branch before the merge?

**Comment by PAPERPANKS** [comment]
@veelenga  well I apologize but i haven't understand what you have asked.

"Could you please just do this on this branch before the merge?"

Can you please explain in more detail.

**Comment by veelenga** [comment]
Sorry, I meant add yourself to the list of contributors. I just did that by myself. Thanks for the PR, good job ;)

**Pull request merged**
