### PR TITLE
Upgrade Amber version

### LINKED ISSUE #32: Upgrade Amber

### PR DESCRIPTION
**Pull request by hugoabonizio**
This upgrades Amber version to v0.2.6 (latest).

I'm not sure I handled the cookies store upgrade the right way, but the spec aren't complaining. I used amberframework/amber#209 as base.

Fix #32

### CODE REVIEW

**Comment by veelenga** [comment]
Wow, @hugoabonizio you are so quick 😄 
Will review this soon!

**Comment by veelenga** [comment]
Hm, interesting, app does not boot on staging:

```crystal
2017-09-19T09:53:40.929129+00:00 heroku[web.1]: Starting process with command `./app`
2017-09-19T09:53:43.598764+00:00 app[web.1]: I, [2017-09-19 09:53:43 +0000 #4]  INFO -- : [96m[Amber 0.2.6][0m serving application "Crystal [ANN] web application." at [96;4mhttp://127.0.0.1:30612[0m
2017-09-19T09:53:43.598785+00:00 app[web.1]: I, [2017-09-19 09:53:43 +0000 #4]  INFO -- : Server started in [33mstaging[0m.
2017-09-19T09:53:43.598818+00:00 app[web.1]: I, [2017-09-19 09:53:43 +0000 #4]  INFO -- : [97mStartup Time 00:00:00.0002010
2017-09-19T09:53:43.598820+00:00 app[web.1]: 
2017-09-19T09:53:43.598820+00:00 app[web.1]: [0m
2017-09-19T09:53:55.099789+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2017-09-19T09:53:55.099789+00:00 heroku[web.1]: Stopping process with SIGKILL
2017-09-19T09:53:55.181465+00:00 heroku[web.1]: Process exited with status 137
2017-09-19T09:54:09.390364+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/" host=crystal-ann-staging.herokuapp.com request_id=f6ccc8fc-65c2-4628-8059-ca88e1613cf1 fwd="194.105.145.92" dyno= connect= service= status=503 bytes= protocol=https
2017-09-19T09:54:41.174863+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2017-09-19T09:54:41.175054+00:00 heroku[web.1]: Stopping process with SIGKILL
2017-09-19T09:54:41.290185+00:00 heroku[web.1]: Process exited with status 137
2017-09-19T09:54:41.304640+00:00 heroku[web.1]: State changed from starting to crashed
2017-09-19T09:54:42.479270+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=crystal-ann-staging.herokuapp.com request_id=99c92d93-70cb-4180-a151-7f1797a15ceb fwd="194.105.145.92" dyno= connect= service= status=503 bytes= protocol=https
2017-09-19T09:54:43.989901+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=crystal-ann-staging.herokuapp.com request_id=c69facc2-2777-4cec-a5a1-2bb7097eb606 fwd="194.105.145.92" dyno= connect= service= status=503 bytes= protocol=https
```

But master branch still works. Will try to figure out... Basically, what deployment does is:

```sh
crystal build --release --no-debug src/crystal-ann.cr -o app
./app --port $PORT
```

which works for me on OS X.

**Comment by hugoabonizio** [comment]
Please check if it's working now.

Maybe it's the same problem as rails/rails#28184, but the default host to bind should already be ```0.0.0.0``` since https://github.com/amberframework/amber/commit/2ad29fc776b81f1eccf15be706632e9f6aa29652 though. :confused:

**Comment by veelenga** [comment]
Yup, that works 🥇 .  Thanks!

**Comment by hugoabonizio** [comment]
:tada:

**Pull request merged**
