### PR TITLE
Move to crystal-announcements org

### PR DESCRIPTION
**Pull request by veelenga**
@hugoabonizio you will need to do:

```sh
$ cd crystal-ann/
$ git remote remove origin
$ git remote add origin https://github.com/crystal-announcements/crystal-ann
```

I left gitter room as is because I haven't found how to change its name to `crystal-announcements/crystal-ann` 😄

### CODE REVIEW

**Comment by hugoabonizio** [comment]
Updated!

About the gitter room, we can create a new one linked to this organization. but I noticed the Kemal's is still ```sdogruyol/kemal``` :smile:

**Comment by hugoabonizio** [comment]
Moved ```autolink.cr``` too :+1:

**Comment by veelenga** [comment]
Great. Could you please update `shard.yml/shard.lock` on this branch as well? Thank you

**Comment by hugoabonizio** [comment]
Done

**Pull request merged**
