### PR TITLE
Add autolink

### LINKED ISSUE #23: Autolink
Crystal's markdown module does not convert plain urls into links:

```crystal
Markdown.to_html "https://example.com" => "<p>https://example.com</p>"
```

so users have to explicitly use markdown syntax `[https://example.com](https://example.com)` submitting an announcement.

The solution might be porting rails' autolink to Crystal:

https://github.com/tenderlove/rails_autolink

### PR DESCRIPTION
**Pull request by hugoabonizio**
Fixes #23

### CODE REVIEW

**Comment by veelenga** [comment]
Awesome 👍 Could you please also add one-two small tests for this to the model suite?

**Comment by veelenga** [comment]
I found one strange case when this does not work. If you insert some html `a` tags into `Announcement.description` as markdown:

```
<a href="hello">http://example.com</a>
```

Then it is converted **to html** as:

```
<p>&lt;a href="hello">http://example.com&lt;/a></p>
```

And **autolink** generates the following:

```
<p>&lt;a href="hello"><a href="http://example.com&lt;/a">http://example.com&lt;/a</a>></p>
```

Which will be shown as:

<p>&lt;a href="hello"><a href="http://example.com&lt;/a">http://example.com&lt;/a</a>></p>

I think this is a bug in `Markdown` module, because it does not escape closing angle `>`. Anyway this is a rare case and maybe we can deal with this later.

**Comment by hugoabonizio** [comment]
@veelenga adding the tests now!

It seems to be the same that happens in this test case:

```crystal
it "encodes html tags" do
  ann = announcement(description: "<script>console.log('hello')</script>")
  expect(ann.content).to eq "<p>&lt;script>console.log('hello')&lt;/script></p>"
end
```

**Comment by veelenga** [comment]
Yeah, i didn't notice it does not escape closing angle, just copy-pasted actual result from the console.

https://github.com/crystal-lang/crystal/commit/fe8f3a3f28d14491ed45958fcac20a1189bc0e10

**Comment by hugoabonizio** [comment]
@veelenga I added a few simple tests and this edge case as pending. Are there other test cases I should write?

**Comment by veelenga** [comment]
No, that looks good. I will experiment a bit with this branch and merge. Thanks a lot

**Comment by hugoabonizio** [comment]
:bowtie:

**Comment by veelenga** [comment]
Deployed and it looks good 👍 Would you like to announce autolink.cr? 😄

**Comment by hugoabonizio** [comment]
I have to write a proper README before announce it, I'll do this asap!

**Comment by veelenga** [comment]
No hurry. Do it whenever you want/have time.

Good job btw. I spent few day unsuccessfully fighting with Crystal regexes trying to do the same 😃

**Comment by hugoabonizio** [comment]
Crystal and Ruby regex are quite different, Ruby has much more weird syntaxes inherited from Perl and I had a bad time porting it too, thank you for the help! :sweat_smile:

**Pull request merged**
